theme = "catppuccin_mocha"

[editor]
auto-save = true
mouse = false
cursorline = true
true-color = true
bufferline = "multiple"
line-number = "relative"
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
ret = ["move_line_down", "goto_line_start"]
X = "extend_line_above"
"}" = "goto_next_paragraph"
"{" = "goto_prev_paragraph"
space = { x = ":buffer-close", c = "toggle_comments"}


[keys.insert]
"A-j"= "move_line_down"
"A-k"= "move_line_up"
"A-h"= "move_char_left"
"A-l"= "move_char_right"
j = { k = "normal_mode" }

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"


[editor.lsp]
display-messages = true

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"