[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt", args = ["+nightly", "--emit=stdout"] }

[language.config]
checkOnSave = { command = "clippy" }
rustfmt.extraArgs = ["+nightly"]

[[language]]
name = "tailwindcss"
scope = "source.css"
injection-regex = "(postcss|css|html)"
file-types = ["css"]
roots = ["tailwind.config.js","tailwind.config.cjs"]
language-server = { command = "tailwindcss-language-server", args = ["-vvv", "--stdio"] }
indent = { tab-width = 2, unit = "  " }
config = { }

[[language]]
name = "vue"
formatter = { command = "prettier", args = ["--parser", "vue"] }
auto-format = true
file-types = ["vue"]
injection-regex = "vue"
shebangs = ["vue"]
language-server = { command = "vue-language-server", args = ["--stdio"] }
roots = ["package.json"]
scope = "text.html.vue"

[language.config.typescript]
tsdk = "/usr/lib/node_modules/typescript/lib"

[[language]]
name = "typescript"
auto-format = true
config = { format = { "semicolons" = "insert", "insertSpaceBeforeFunctionParenthesis" = true } }

[[language]]
name = "toml"
language-server = { command = "" }